server:
  port: 9090
#  servlet:
#    context-path: /gem-auction
#
spring:
  datasource:
    username: admin
    password: madushan
    url: jdbc:mysql://web-auction.ctekyq0ku4uu.ap-northeast-1.rds.amazonaws.com:3306/gem_auction
  jpa:
    hibernate:
      ddl-auto: none

