server:
  port: 9090
#  servlet:
#    context-path: /gem-auction
spring:
  datasource:
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
    url: jdbc:mysql://${DB-HOST}:${DB-PORT}/${DB-NAME}
  jpa:
    hibernate:
      ddl-auto: ${DDL-AUTO}

